### ISSUE TITLE
Error when enabling the theme on a tenant (not root)

### ISSUE THREAD

**Issue by dcinzona** [OnefoursevenLabs/AdminLTE#1]
I downloaded the theme and added it to my project, then created a new tenant on my localhost.  The tenant works fine with the default theme-machine, but when I enable this theme I get an error when trying to load the resources defined in the manifest:
`manifest.DefineStyle("Bootstrap").SetUrl("boostrap/css/bootstrap.min.css", "boostrap/css/bootstrap.css").SetVersion("3.3.5").SetCdn("//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css", "//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.css", true);`
```A 'stylesheet' named 'Bootstrap' could not be found.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: A 'stylesheet' named 'Bootstrap' could not be found.```

The files are there and I haven't made any modifications to the theme at all.  Could this be a bug with Orchard or the theme?

**Comment by SzymonSel** [comment]
Yup, I can see there's a typo in the manifest file. Let me fix that for ya real, quick.

**Comment by dcinzona** [comment]
So, my issue was actually because the folder containing the theme did not match the name of the DLL.  but if there are typos, I guess fixing those too would be good anyway. :)

**Comment by SzymonSel** [comment]
:)
